spring.application.name=GoodReadsPL
spring.datasource.url=jdbc:postgresql://localhost:5432/GoodReadsPL
spring.datasource.username=melkowskiphilip
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Locale i i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8

jwt.secret=+QWh8p0Ps0U4a5JG/8MJN+117PnVSGLib36B8Yh6RY0=
jwt.expiration=900000

# mail - mailtrap na czas dewelopmentu
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6cc76a947117b3
spring.mail.password=5f99cc884bbce6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=no-reply@goodreadspl.com


logging.level.org.springframework.security=DEBUG