spring.application.name=GoodReadsPL
spring.datasource.url=jdbc:postgresql://localhost:5432/GoodReadsPL
spring.datasource.username=melkowskiphilip
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Locale i i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8

jwt.secret=+QWh8p0Ps0U4a5JG/8MJN+117PnVSGLib36B8Yh6RY0=
jwt.expiration=900000